const ACTION_TYPE = {
    // API REQUESTING
    APP_STARTING: 'APP_STARTING',
    DO_SOMETHING: 'DO_SOMETHING',
    UPDATE_LOGIN_INFO: 'UPDATE_LOGIN_INFO',
    USER_LOGIN: 'USER_LOGIN',
    USER_LOGOUT: 'USER_LOGOUT',
    USER_LOGGED_IN: 'USER_LOGGED_IN',


    // UI ANIMATION,
    FETCHING_DATA: 'FETCHING_DATA' 
};

export default ACTION_TYPE;