const ACTION_TYPE = {
    // API REQUESTING
    APP_STARTING: 'APP_STARTING',
    DO_SOMETHING: 'DO_SOMETHING',
    UPDATE_LOGIN_INFO: 'UPDATE_LOGIN_INFO',
    SIGNUP_USER: 'SIGNUP_USER',
    USER_LOGIN: 'USER_LOGIN',
    USER_LOGOUT: 'USER_LOGOUT',
    USER_LOGGED_IN: 'USER_LOGGED_IN',
    APARTMENTS_GETTING: 'APARTMENTS_GETTING',
    APARTMENTS_GETTING_NEXT_PAGE: 'APARTMENTS_GETTING_NEXT_PAGE',
    MY_APARTMENTS_GETTING: 'MY_APARTMENTS_GETTING',
    MY_APARTMENTS_GETTING_NEXT_PAGE: 'MY_APARTMENTS_GETTING_NEXT_PAGE',
    MY_APARTMENTS_RELOADING: 'MY_APARTMENTS_RELOADING',
    APARTMENT_GETTING: 'APARTMENT_GETTING',
    COMMENTS_GETTING: 'COMMENTS_GETTING',
    COMMENT_CREATING: 'COMMENT_CREATING',
    DISTRICTS_GETTING: 'DISTRICTS_GETTING',
    WARDS_GETTING: 'WARDS_GETTING',
    STREETS_GETTING: 'STREETS_GETTING',
    FILTER_SETTING: 'FILTER_SETTING',
    FILTER_RESETTING: 'FILTER_RESETTING',
    UPDATE_USER_INFORMATION: 'UPDATE_USER_INFORMATION',
    CHANGE_PASSWORD: 'CHANGE_PASSWORD',
    PARAMS_GETTING: 'PARAMS_GETTING',

    ERROR_OCCURRING: 'ERROR_OCCURRING',

    // UI ANIMATION,
    FETCHING_APARTMENTS: 'FETCHING_APARTMENTS',
    FETCHING_APARTMENT: 'FETCHING_APARTMENT',
    CREATING_COMMENT: 'CREATING_COMMENT',
    CREATING_APARTMENT: 'CREATING_APARTMENT',
    UPDATING_APARTMENT: 'UPDATING_APARTMENT',
    CHECKING_LOGIN: 'CHECKING_LOGIN',
    CHANGING_APARTMENT_STATUS: 'CHANGING_APARTMENT_STATUS',
    DELETING_APARTMENT: 'DELETING_APARTMENT',
    OPENED_APP: 'OPENED_APP'
};

export default ACTION_TYPE;